version: "3"

services:
  redpanda-console:
    image: docker.redpanda.com/vectorized/console:latest
    container_name: redpanda-console
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Tokyo
      KAFKA_BROKERS: ${KAFKA_BROKERS:?KAFKA_BROKERS not defined}
